package com.lrh.mapper;

import com.lrh.model.House;
import com.lrh.model.HouseExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.session.RowBounds;

public interface HouseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    long countByExample(HouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    int deleteByExample(HouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    @Delete({
        "delete from house",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    @Insert({
        "insert into house (room_num, city, ",
        "community_id, community_name, ",
        "building_id, building_name, ",
        "floor, house_type, ",
        "owner, mobile, enable)",
        "values (#{roomNum,jdbcType=VARCHAR}, #{city,jdbcType=VARCHAR}, ",
        "#{communityId,jdbcType=BIGINT}, #{communityName,jdbcType=VARCHAR}, ",
        "#{buildingId,jdbcType=BIGINT}, #{buildingName,jdbcType=VARCHAR}, ",
        "#{floor,jdbcType=INTEGER}, #{houseType,jdbcType=VARCHAR}, ",
        "#{owner,jdbcType=VARCHAR}, #{mobile,jdbcType=VARCHAR}, #{enable,jdbcType=BIT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(House record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    int insertSelective(House record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    List<House> selectByExampleWithRowbounds(HouseExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    List<House> selectByExample(HouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    @Select({
        "select",
        "id, room_num, city, community_id, community_name, building_id, building_name, ",
        "floor, house_type, owner, mobile, enable",
        "from house",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.lrh.mapper.HouseMapper.BaseResultMap")
    House selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") House record, @Param("example") HouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    int updateByExample(@Param("record") House record, @Param("example") HouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    int updateByPrimaryKeySelective(House record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    @Update({
        "update house",
        "set room_num = #{roomNum,jdbcType=VARCHAR},",
          "city = #{city,jdbcType=VARCHAR},",
          "community_id = #{communityId,jdbcType=BIGINT},",
          "community_name = #{communityName,jdbcType=VARCHAR},",
          "building_id = #{buildingId,jdbcType=BIGINT},",
          "building_name = #{buildingName,jdbcType=VARCHAR},",
          "floor = #{floor,jdbcType=INTEGER},",
          "house_type = #{houseType,jdbcType=VARCHAR},",
          "owner = #{owner,jdbcType=VARCHAR},",
          "mobile = #{mobile,jdbcType=VARCHAR},",
          "enable = #{enable,jdbcType=BIT}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(House record);
}