package com.lrh.model;

import java.io.Serializable;

public class House implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.id
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.room_num
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    private String roomNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.city
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.community_id
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    private Long communityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.community_name
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    private String communityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.building_id
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    private Long buildingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.building_name
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    private String buildingName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.floor
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    private Integer floor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.house_type
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    private String houseType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.owner
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    private String owner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.mobile
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.enable
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    private Boolean enable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table house
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.id
     *
     * @return the value of house.id
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    public House withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.id
     *
     * @param id the value for house.id
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.room_num
     *
     * @return the value of house.room_num
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    public String getRoomNum() {
        return roomNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    public House withRoomNum(String roomNum) {
        this.setRoomNum(roomNum);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.room_num
     *
     * @param roomNum the value for house.room_num
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    public void setRoomNum(String roomNum) {
        this.roomNum = roomNum == null ? null : roomNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.city
     *
     * @return the value of house.city
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    public House withCity(String city) {
        this.setCity(city);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.city
     *
     * @param city the value for house.city
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.community_id
     *
     * @return the value of house.community_id
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    public Long getCommunityId() {
        return communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    public House withCommunityId(Long communityId) {
        this.setCommunityId(communityId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.community_id
     *
     * @param communityId the value for house.community_id
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    public void setCommunityId(Long communityId) {
        this.communityId = communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.community_name
     *
     * @return the value of house.community_name
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    public String getCommunityName() {
        return communityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    public House withCommunityName(String communityName) {
        this.setCommunityName(communityName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.community_name
     *
     * @param communityName the value for house.community_name
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    public void setCommunityName(String communityName) {
        this.communityName = communityName == null ? null : communityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.building_id
     *
     * @return the value of house.building_id
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    public Long getBuildingId() {
        return buildingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    public House withBuildingId(Long buildingId) {
        this.setBuildingId(buildingId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.building_id
     *
     * @param buildingId the value for house.building_id
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    public void setBuildingId(Long buildingId) {
        this.buildingId = buildingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.building_name
     *
     * @return the value of house.building_name
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    public String getBuildingName() {
        return buildingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    public House withBuildingName(String buildingName) {
        this.setBuildingName(buildingName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.building_name
     *
     * @param buildingName the value for house.building_name
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    public void setBuildingName(String buildingName) {
        this.buildingName = buildingName == null ? null : buildingName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.floor
     *
     * @return the value of house.floor
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    public Integer getFloor() {
        return floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    public House withFloor(Integer floor) {
        this.setFloor(floor);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.floor
     *
     * @param floor the value for house.floor
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    public void setFloor(Integer floor) {
        this.floor = floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.house_type
     *
     * @return the value of house.house_type
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    public String getHouseType() {
        return houseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    public House withHouseType(String houseType) {
        this.setHouseType(houseType);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.house_type
     *
     * @param houseType the value for house.house_type
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    public void setHouseType(String houseType) {
        this.houseType = houseType == null ? null : houseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.owner
     *
     * @return the value of house.owner
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    public House withOwner(String owner) {
        this.setOwner(owner);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.owner
     *
     * @param owner the value for house.owner
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.mobile
     *
     * @return the value of house.mobile
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    public House withMobile(String mobile) {
        this.setMobile(mobile);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.mobile
     *
     * @param mobile the value for house.mobile
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.enable
     *
     * @return the value of house.enable
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    public Boolean getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    public House withEnable(Boolean enable) {
        this.setEnable(enable);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.enable
     *
     * @param enable the value for house.enable
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house
     *
     * @mbg.generated Thu Jul 25 22:20:56 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", roomNum=").append(roomNum);
        sb.append(", city=").append(city);
        sb.append(", communityId=").append(communityId);
        sb.append(", communityName=").append(communityName);
        sb.append(", buildingId=").append(buildingId);
        sb.append(", buildingName=").append(buildingName);
        sb.append(", floor=").append(floor);
        sb.append(", houseType=").append(houseType);
        sb.append(", owner=").append(owner);
        sb.append(", mobile=").append(mobile);
        sb.append(", enable=").append(enable);
        sb.append("]");
        return sb.toString();
    }
}